---
enabled: false
create: false
fullnameOverride: ""
broker: ""
port: 5672

labels: {}
#  key: value

selectorLabels: {}
#  key: value

# check https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/examples/users
users: []
#- name: ""
#  spec: {}

# check https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/examples/queues
queues: []
#- name: ""
#  spec: {}

# Exchanges and Topics
# check https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/examples/topic-exchanges
#   and https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/examples/exchanges
exchanges: []
#- name: ""
#  spec: {}

# check https://github.com/rabbitmq/messaging-topology-operator/blob/main/docs/examples/policies/policy.yaml
policies: []
#- name: ""
#  spec: {}

# check https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/examples/permissions
permissions: []
#- name: ""
#  spec: {}

# check https://github.com/rabbitmq/messaging-topology-operator/blob/main/docs/examples/vhosts/vhost.yaml
virtualHosts: []
#- name: ""
#  spec: {}

# check https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/examples/bindings
bindings: []
#- name: ""
#  spec: {}

# check https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/examples/federations
federations: []
#- name: ""
#  spec: {}
#  uri: 
#    host: changeme
#    vhost: ""
#    query: ""
#    port: 5672
#    username: changeme
#    password: changeme

# check https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/examples/shovels
shovels: []
#- name: ""
#  spec: {}
#  srcUri: 
#    host: changeme
#    vhost: ""
#    query: ""
#    port: 5672
#    username: changeme
#    password: changeme
#  destUri: 
#    host: changeme
#    vhost: ""
#    query: ""
#    port: 5672
#    username: changeme
#    password: changeme
