apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webservice.fullname" . }}-sso
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
stringData:
  URI: {{ .Values.sso.uri }}
  USER_NAME_ATTRIBTUE: {{ .Values.sso.userNameAttribute }}
  CLIENT_ID: {{ .Values.sso.client.id }}
  SECRET: {{ .Values.sso.client.secret }}