{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.secrets }}
---
# noinspection KubernetesUnknownResourcesInspection
kind: ExternalSecret
# noinspection KubernetesUnknownResourcesInspection
apiVersion: external-secrets.io/v1alpha1
metadata:
  name: {{ include "microservice.fullname" $ }}-{{ .namePostfix }}
  labels:
    {{- include "microservice.labels" $ | nindent 4 }}
    {{- toYaml $.Values.externalSecrets.labels | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
  {{- if or ($.Values.externalSecrets.annotations) (.annotations) }}
  annotations:
    {{- toYaml $.Values.externalSecrets.annotations | nindent 4 }}
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}

{{ end }}
{{- end }}