{{- if .Values.sso.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "microservice.fullname" . }}-sso-config
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
stringData:
  ISSUER: {{ .Values.sso.issuerUri }}
  CLIENT_ID: {{ .Values.sso.clientId }}
  CLIENT_SECRET: {{ .Values.sso.clientSecret }}
  SCOPES: {{ .Values.sso.scopes }}
  USERNAME_ATTRIBUTE: {{ .Values.sso.userNameAttribute }}
  ROLE_ATTRIBUTE: {{ .Values.sso.roleAttribute }}
{{- end }}
