{{- if .Values.vaultSecrets.enabled }}
{{- range $s := .Values.vaultSecrets.secrets }}
---
# noinspection KubernetesUnknownResourcesInspection
kind: ExternalSecret
# noinspection KubernetesUnknownResourcesInspection
apiVersion: external-secrets.io/v1
metadata:
  name: {{ include "microservice.fullname" $ }}-{{ $s.namePostfix }}
  labels:
    {{- include "microservice.labels" $ | nindent 4 }}
    {{- with $.Values.vaultSecrets.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $s.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or ($.Values.vaultSecrets.annotations) ($s.annotations) }}
  annotations:
    {{- with $.Values.vaultSecrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $s.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  refreshInterval: {{ $s.refreshInterval }}
  secretStoreRef:
    {{- toYaml $s.secretStoreRef | nindent 4 }}
  target:
    creationPolicy: {{ $s.creationPolicy }}
    deletionPolicy: {{ $s.deletionPolicy }}
    name: "{{ include "microservice.fullname" $ }}-{{ $s.namePostfix }}"
  data:
    {{- range $i := $s.items }}
    - secretKey: {{ $i.secretKey | quote }}
      remoteRef:
        conversionStrategy: {{ $s.conversionStrategy }}
        decodingStrategy: {{ $s.decodingStrategy }}
        key: {{ $i.vaultKey | quote }}
        metadataPolicy: {{ $s.metadataPolicy }}
        property: {{ $i.vaultProperty | quote }}
    {{- end }}

{{ end }}
{{- end }}