title = "KP-COMMONS"
baseURL = "/"

languageCode = "en-uk"
defaultContentLanguage = "en"

# remove tags and categories pages
disableKinds = ["taxonomy", "taxonomyTerm"]

theme = "learn"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"

[Blackfriday]
# opens absolute links in a new window or tab
hrefTargetBlank = true

[markup.goldmark.renderer]
unsafe = true

[Languages]
[Languages.en]
title = "KP-COMMONS"
weight = 1
languageName = "English"
[Languages.de]
title = "KP-COMMONS"
weight = 2
languageName = "Deutsch"


[[menu.shortcuts]]
name = "<i class='fas fa-user-circle'></i> Über den Autor"
url = "/author/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Quelltexte (GitHub)"
identifier = "ds"
url = "https://github.com/KaiserpfalzEDV/kp-commons"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-info-circle'></i> Impressum"
url = "/impressum/"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-user-circle'></i> About the author"
url = "/author/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Source code (GitHub)"
identifier = "ds"
url = "https://github.com/KaiserpfalzEDV/kp-commons"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-info-circle'></i> Site Notice"
url = "/impressum/"
weight = 12
