#
# Copyright (c) 2021 Kaiserpfalz EDV-Service, Roland T. Lichti.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
sms77_io: &sms77_io-api
  url: ${SMS77_API_URL}
  scope: javax.inject.Singleton

sms77_io-mock: &sms77_io-api-mock
  url: https://localhost:9083/
  scope: javax.inject.Singleton

sms77:
  token: ${SMS77_API_KEY:this is an invalid token}

quarkus:
  rest-client:
    "de.kaiserpfalzedv.commons.external.sms77.client.Sms77Client": *sms77_io-api

  http:
    test-port: 9083

"%test":
  quarkus:
    rest-client:
      "de.kaiserpfalzedv.commons.external.sms77.client.Sms77Client": *sms77_io-api-mock