{{- if .Values.enabled }}
    {{- with .Values.exchanges }}
---
kind: Exchange
apiVersion: rabbitmq.com/v1beta1
metadata:
    name: {{ .name | quote }}
    labels:
        {{- include "rabbitmq.labels" . | nindent 8 }}
spec:
    {{ .spec | toYaml | nindent 4 }}
    rabbitmqClusterReference:
        name: {{ include "rabbitmq.reference" . }}
    {{- end }}
{{ end }}
