{{- if .Values.enabled }}
    {{- with .Values.federations }}
---
kind: Federation
apiVersion: rabbitmq.com/v1beta1
metadata:
    name: {{ .name | quote }}
    labels:
        {{- include "rabbitmq.labels" . | nindent 8 }}
spec:
    {{ .spec | toYaml | nindent 4 }}
    uriSecret:
        name: {{ .name }}-uri-secret

    rabbitmqClusterReference:
        name: {{ include "rabbitmq.reference" . }}

---
        {{- $vhost := "" }}
        {{- if .uri.vhost }}
            {{- $vhost = printf "/%s" .uri.vhost }}
        {{- end }}
        {{- $query := "" }}
        {{- if .uri.query }}
            {{- $query = printf "?%s" .uri.query }}
        {{- end}}
        {{- $uri := printf "amqp://%s:%s@%s:%s%s%s" .uri.username .uri.password .uri.host .uri.port $vhost $query }}
kind: Secret
type: Opaque
apiVersion: v1
metadata:
    name: {{ .name }}-uri-secret
    labels:
        {{- include "rabbitmq.labels" . | nindent 8 }}
stringData:
    uri: {{ $uri | quote }}

    {{- end }}
{{ end }}
