{{- if .Values.ingress.enabled -}}
{{- $fullName := include "rabbitmq.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
# noinspection KubernetesNonEditableResources
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- if .Values.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.tls.clusterIssuer }}
    cert-manager.io/duration: {{ .Values.tls.duration | default "2160h"}}
    cert-manager.io/renew-before: {{ .Values.tls.renewBefore | default "1728h" }}
    cert-manager.io/usages: "server auth"
    cert-manager.io/revision-history-limit: "5"
    cert-manager.io/private-key-algorithm: "ECDSA"
    cert-manager.io/private-key-size: "521"
      {{- with first .Values.ingress.hosts }}
    cert-manager.io/common-name: {{ . }}
      {{- end }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.tls }}
  tls:
    {{- if .Values.tls.enabled }}
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ $fullName }}-tls
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 15672
    {{- end }}
{{- end }}
