{{- if and (.Values.enabled) (.Values.create) -}}
---
kind: RabbitmqCluster
apiVersion: rabbitmq.com/v1beta1
metadata:
  name: {{ include "rabbitmq.broker" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
{{- if .spec }}
spec:
  {{ .spec | toYaml | nindent 2 }}
{{- end }}
{{ end }}
