{{- if and (.Values.enabled) (.Values.create) -}}
---
kind: RabbitmqCluster
apiVersion: rabbitmq.com/v1beta1
metadata:
{{- if $.Values.broker }}
  name: {{ $.Values.broker }}
{{- else }}
  name: {{ include "rabbitmq.fullname" . }}
{{- end }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
{{- if .spec }}
spec:
  {{ .spec | toYaml | nindent 2 }}
{{- end }}
{{ end }}
