{{- if .Values.enabled }}
{{- range .Values.users }}
---
kind: User
apiVersion: rabbitmq.com/v1beta1
metadata:
  name: {{ include "rabbitmq.fullname" $ }}-{{ .name }}
  labels:
    {{- include "rabbitmq.labels" $ | nindent 4 }}
spec:
  {{- .spec | toYaml | nindent 2 }}
  rabbitmqClusterReference:
    name: {{ include "rabbitmq.broker" $ }}
{{- end }}
{{ end }}
