:adr-title: SQL based data store
:adr-state: Accepted
:adr-date: 2024-10-04
:adr-expires: ./.
:adr-author: klenkes74
:adr-body: klenkes74
:adr-seq: 004
:adr-short: MADR-{adr-seq}
= {adr-short} -- {adr-title}

(((Architectural Decisions, {adr-short})))
(((Architectural Decisions, {adr-title})))
((({adr-short})))
((({adr-title})))

[cols="<.<8h,<.<12a", frame="topbot", grid="rows"]
|===
| ADR | {adr-short}
| Title | {adr-title}
| State | {adr-state}
| Author | {adr-author}
| Decision Body | {adr-body}
| Valid from | {adr-date}
| Expires | {adr-expires}
|===

include::partial$config.adoc[]


== Context
The default data store for the DCIS is a relational database.
There are different approaches to handle RDBMs in java.

There may be other datastores (so called no-sql).
These are neither handled by this ADR nor forbidden to be used in this project.


== Decision
To handle SQL databases we use JPA.
It is a quite well known standard and well supported within the java ecosystem.
For spring we use the spring-data-jpa framework to handle the low level OR mapping.


== Consequences
1. There is no low level efficiency optimization to our queries.
2. The restrictions of spring-data-jpa apply.

<<<
