apiVersion: v2
name: microservice
description: A spring-boot microservice with a postgresql database backend (managed by PGO) and RabbitMQ rabbitmq.

type: application
version: 2.0.3

dependencies:
- name: postgresql
  condition: postgresql.enabled
  version: "16.0.6"
  repository: "https://charts.bitnami.com/bitnami"
- name: rabbitmq
  condition: rabbitmq.enabled
  version: "1.0.0"
  repository: "oci://quay.io/kaiserpfalzedv/helm"
