apiVersion: v2
name: microservice
description: A spring-boot microservice with a postgresql database backend (managed by PGO)

type: application
version: 1.0.0

dependencies:
- name: postgrescluster
  condition: postgrescluster.enabled
  version: "5.6.0"
  repository: "oci://quay.io/kaiserpfalzedv/helm"