nameOverride: ""
fullnameOverride: ""
partOf: &partOf ""
version: "0.0.1+changeme"

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  fsGroupChangePolicy: OnRootMismatch


securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

metrics:
  enabled: true
  port: 8081

probes:
  enabled: true
  default: true


resources:
  limits:
    cpu: '2'
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1280Mi

tmpSize: 500Mi

mounts: {}

replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

service:
  enabled: true
  type: ClusterIP
  port: 8080
  containerPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - host: chart-example.local
    paths:
      - path: /
        pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

postgrescluster:
  enabled: false
  port: 5432
  postgresVersion: 15
  pgBouncerReplicas: 1
  monitoring: true

  instanceName: db
  instanceSize: 2Gi
  instanceMemory: 1Gi
  instanceCPU: 1000m
  instanceReplicas: 1

  openshift: true
  partOf: *partOf

sso:
  enabled: false
  issuerUri: https://changeme/
  clientId: changeme
  clientSecret: changeme
  scopes: openid,profile,email,roles
  userNameAttribute: preferred_username
  roleAttribute: roles

rabbitmq:
  enabled: false
  broker: 
    create: false
    name: changeme
    uri: changeme
    port: 5672
  labels: {}
  partOf: *partOf

applicationConfig:
  enabled: false
  type: yaml
  data:
    application:
      name: changeme
