nameOverride: ""
fullnameOverride: ""
partOf: &partOf ""
version: "0.0.1+changeme"

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

env: []
envFrom: []

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  fsGroupChangePolicy: OnRootMismatch


securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  automount: false
  annotations: {}
  name: ""

metrics:
  enabled: true
  port: 8081

probes:
  enabled: true
  default: true
  startup: {}
  liveness: {}
  readiness: {}


resources:
  limits:
    cpu: '2'
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1280Mi

mounts: []
#  - name: changeme
#    mountPath: /changeme
#    subPath: changeme
#    readOnly: true
#    spec:
#      emptyDir: {}
#      configMap: {}
#      secret: {}
#      projected: {}

database:
  enabled: false
  labels: {}
  annotations: {}
  size: "1Gi"
  walSize: "1Gi"
  storageClass: "nfs"
  version: 17
  instances: 1
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  
vaultSecrets:
  enabled: false
  automount: false
  annotations: {}
  labels: {}
  secrets:
  - namePostFix: changeme
    automount: false
    keyPrefix: ""
    secretStoreRef:
      kind: ClusterSecretStore
      name: changeme
    items:
      - secretKey: changeme
        vaultKey: changeme
        vaultProperty: changeme
    annotations: {}
    labels: {}
    conversionStrategy: Default
    decodingStrategy: None
    metadataPolicy: None
    creationPolicy: Owner
    deletionPolicy: Retain
    refreshInterval: 30m

externalSecrets:
  enabled: false
  automount: false
  annotations: {}
  labels: {}
  secrets:
  - namePostfix: changeme
    automount: false
    keyPrefix: ""
    annotations: {}
    labels: {}
    spec:
      data:
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: changeme
          metadataPolicy: None
          property: changme
        secretKey: changeme
      refreshInterval: 30m
      secretStoreRef:
        kind: SecretStore
        name: changeme
      target:
        creationPolicy: Owner
        deletionPolicy: Retain
        name: changeme
        
externalDb: {}

tmpSize: 500Mi

replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

service:
  enabled: true
  type: ClusterIP
  port: 8080
  containerPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - host: chart-example.local
    paths:
      - path: /
        pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


applicationConfig:
  enabled: false
  type: yaml
  data:
    application:
      name: changeme
