name: Java Runner OCI Image

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'kp-java-runner/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ORG_USER }}
          password: ${{ secrets.QUAY_ORG_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: kp-java-runner
          dockerfile: Dockerfile
          enableBuildKit: true
          platforms: linux/amd64
          push: true
          tags: quay.io/kaiserpfalzedv/java-runner:21-latest,quay.io/kaiserpfalzedv/java-runner:21-${{ github.ref_name }}
          outputs: type=image,name=target
