## This is basic continuous integration build for your Quarkus application.

name: Create Github Pages

on:
  workflow_dispatch:


jobs:
  github-pages:
    name: Create and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout sources
        id: checkout-sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        id: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        id: setup-maven
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [
              { "id": "nvdApi", "username": "klenkes74", "password": "${{ secrets.NVD_API_KEY }}"},
              { "id": "github", "username": "${{ GITHUB_ACTOR }}", "password": "${{ secrets.GITHUB_TOKEN }}"}
            ]

      - name: Prepare GPG signing
        id: install-gpg-key
        run: |
          echo -en "${{ secrets.GPG_SIGNING_KEY }}\n" | gpg --batch --import || true
          gpg --list-secret-keys --keyid-format LONG || true

      - name: Prepare checkstyle for site generation
        id: prepare-checkstyle
        run: |
          mvn \
            --batch-mode \
            --no-transfer-progress \
            \
            -pl kp-checkstyle \
            \
            install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: site
        id: build-site
        run: |
          mvn \
            --batch-mode \
            --no-transfer-progress \
            \
            -Prelease \
            -Dgpg.passphrase=${{ secrets.GPG_SECRET }} \
            \
            site site:stage scm-publish:publish-scm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
