## This is basic continuous integration build for your Quarkus application.

name: Github Pages

on:
  push:
    branches: [ main ]

jobs:
  github-pages:
    runs-on: [ java ]
    steps:
      - name: Checkout sources
        id: checkout-sources
        uses: actions/checkout@v2

      - name: Set up JDK 11
        id: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        id: build-java
        run: mvn --batch-mode site -Pproduction,site,release

      - name: check-dirs
        run: |
          echo -n "Directory: " ; pwd
          ls -la $(pwd)/target/site
          ls -la
          find . -name "site"

      - name: Update github pages
        id: update-github-pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          workspace: /home/runner/_work/kp-commons/kp-commons
          folder: target/site