name: Helm Chart Webservice

on:
  push:
    branches:
      - main
    paths:
      - helm/webservice
  pull_request:
    branches:
      - main
    paths:
      - helm/webservice
  workflow_dispatch:

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ORG_USER }}
          password: ${{ secrets.QUAY_ORG_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: kp-java-runner
          dockerfile: Dockerfile
          enableBuildKit: true
          platforms: linux/amd64
          push: true
          tags: quay.io/kaiserpfalzedv/helm/mitmproxy:1.0.0,quay.io/kaiserpfalzedv/helm/mitmproxy:${{ github.ref_name }}
          outputs: type=image,name=target
