## This is basic continuous integration build for your Quarkus application.

name: Github Pages

on:
  release:
    types: [created]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        id: checkout-sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        id: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Prepare GPG signing
        id: install-gpg-key
        run: |
          cat < (echo -e "${{ secrets.GPG_SIGNING_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Set up Maven
        id: setup-maven
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{ "id": "nvdApi", "username": "egal", "password": "${{ secrets.NVD_API_KEY }}"}]

      - name: Build
        id: build-java
        run: |
          mvn \
            --batch-mode \
            --no-transfer-progress \
            \
            -Prelease
            -Dgpg.passphrase=${{ secrets.GPG_SECRET }} \
            \
            install
        
      - name: site
        id: build-site
        run: |
          mvn \
            --batch-mode \
            --no-transfer-progress \
            \
            -Prelease
            \
            site site:stage scm-publish:publish-scm
