## This is basic continuous integration build for your Quarkus application.

name: Github Pages

on:
  release:
    types: [created]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        id: checkout-sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build
        id: build-java
        run: mvn --batch-mode --no-transfer-progress deploy site site:stage scm-publish:publish-scm
